on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: 18 }

      - run: npm ci
      - run: npm run build

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & push Docker image
        run: |
          docker build -t \
            us-central1-docker.pkg.dev/notely-464120/notely-ar-repo/myfirstimage:latest .
          docker push us-central1-docker.pkg.dev/notely-464120/notely-ar-repo/myfirstimage:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-464120/notely-ar-repo/myfirstimage:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-464120 \
            --max-instances=4