name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    # make your Turso URL + token available to drizzle.config.ts
    env:
      TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
      TURSO_AUTH_TOKEN:     ${{ secrets.TURSO_AUTH_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Run database migrations
        run: npx drizzle-kit migrate

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker credential helper
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & push Docker image
        run: |
          docker build \
            -t us-central1-docker.pkg.dev/notely-464120/notely-ar-repo/myfirstimage:latest .
          docker push \
            us-central1-docker.pkg.dev/notely-464120/notely-ar-repo/myfirstimage:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-464120/notely-ar-repo/myfirstimage:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-464120 \
            --max-instances=4
